logging:
  level:
    com.aligntech.inventory: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  profiles: development
server:
  port: 8080

---
spring:
  profiles: production
server:
  port: 80